name: realdex
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch==1.13.0+cu117
    - torchvision==0.14.0+cu117
    - torchaudio==0.13.0+cu117
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - pytorch3d --find-links https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt1130/download.html
    - torch-geometric==2.2.0
    - torch-scatter==2.0.9 --find-links https://data.pyg.org/whl/torch-1.13.0+cu117.html
    - torch-sparse==0.6.13 --find-links https://data.pyg.org/whl/torch-1.13.0+cu117.html
    - torch-cluster==1.6.0 --find-links https://data.pyg.org/whl/torch-1.13.0+cu117.html
    - opencv-python==4.8.0.76
    - numpy==1.24.4
    - scipy==1.10.0
    - matplotlib==3.5.1
    - scikit-learn==1.3.0
    - pytorch-lightning==2.0.8
    - hydra-core==1.3.2
    - transforms3d==0.4.1
    - trimesh==3.9.8
    - plotly==5.14.1
    - healpy==1.16.2
    - h5py
    - lxml==4.9.2
    - ipython
    - ipdb
    - tqdm
